/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_test_JniLogger */

#ifndef _Included_com_test_JniLogger
#define _Included_com_test_JniLogger
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_test_JniLogger
 * Method:    createNewLogger
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_test_JniLogger_createNewLogger
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
