/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_test_JniBridge */

#ifndef _Included_com_test_JniBridge
#define _Included_com_test_JniBridge
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_test_JniBridge
 * Method:    version
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_test_JniBridge_version
  (JNIEnv *, jclass);

/*
 * Class:     com_test_JniBridge
 * Method:    build
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_test_JniBridge_build
  (JNIEnv *, jclass);

/*
 * Class:     com_test_JniBridge
 * Method:    nativeCalculateSquares
 * Signature: ([JI)[J
 */
JNIEXPORT jlongArray JNICALL Java_com_test_JniBridge_nativeCalculateSquares
  (JNIEnv *, jclass, jlongArray, jint);

#ifdef __cplusplus
}
#endif
#endif
